config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  
  validates :title, length: {minimum: 3, maximum: 50}
  validates :description, length: {minimum: 3, maximum: 5000}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  
  before_save { self.email = email.downcase }
  
  VALIDATE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 2, maximum: 50}
  validates :email, presence: true,  uniqueness: {case_sensitive: false}, 
      format: {with: VALIDATE_EMAIL_REGEX}, length: {minimum: 3, maximum: 255}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :show, :update, :destroy]
  
  def index
    @articles = Article.all
  end
  
  def new
      @article = Article.new
  end
  
  def create
    # render plain: params[:article].inspect
    
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:success] = "article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
    
  end
  
  def show
  end
  

  def edit
    @article = Article.find(params[:id])
  end
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    flash[:danger] = "Article was successfully destroyed"
    redirect_to articles_path
  end
  
  private 
    def set_article
          @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', objError: @article %>

<div class="row">
  <div class="col-xs-12">
    
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <%= f.label :title, class: "col-sm-2 control-label" %> 
        <div class="col-sm-10">
          <%= f.text_field :title, class: "control-field", placeholder: "Article Title", autofocus: true %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :description, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_area :description, rows: 10, class: "control-field", placeholder: "Article description" %>
        </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    

  <% end %>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      [ <%= link_to "Cancel and return to Article listing", articles_path %> ]
    </div>
  </div>
  
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="left">Edit Existing article</h1>


<%= render "form" %>

app/views/articles/index.html.erb
<h1 align="center">Listing all Articles</h1>

<% @articles.each do |article| %>
<div class="row">
  <div class="col-xs-12">
    <div class="well well-lg">
      <div>
        <%= link_to article.title, article_path(article), class: "article-title" %>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs" %> |
          <%= link_to "Delete", article_path(article), method: :delete,
                      data: { confirm: "Are you sure you want to delete the article?"},
                      class: "btn btn-xs" %>
        <div class="article-meta-details">
          <small>Created by: <%= article.user.username if article.user %>, 
          <%= time_ago_in_words(article.user.created_at) if article.user %>
          Updated at: <%= time_ago_in_words(article.user.updated_at)  if article.user %>
          </small>
        </div>
      </div>
      
      <div class="article-body">
          <%= truncate(article.description, length: 100) %>
      </div>      
    </div>
  </div>
</div>
<% end %>
  

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h2> Title: <%= @article.title %></h2>
<div class="col-xs-12 ">
  <%= simple_format(@article.description) %>
  <div class="article-show-actions">
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs" %>
    <%= link_to "Delete this article", article_path(@article), method: :delete,
                data: { confirm: "Are you sure you want to delete the article?"},
                class: "btn btn-xs" %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; Baljinder
    </small>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
    </div>
</div>
  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
    
  <%= link_to "Alpha blog", root_path, class: "text-center navbar-brand", id: "logo"  %>
  
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Articles", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "About", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>About page</p>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="text-center jumbotron">
  <h1>ALPHA BLOG</h1>
  <%= link_to 'Sign up now', "#", class: "btn btn-primary btn-lg" %>
</div>

app/views/shared/_errors.html.erb
  <% if objError.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@article.errors.count, "error") %>              
                prevented the article from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% objError.errors.full_messages.each do |msg| %>
                  <li> <%= msg %> </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>